# x-crack 配置文件
version: "1.0.0"
debug: false
log_level: "info"

# 爆破设置
brute:
  # 并发控制
  target_concurrent: 50
  task_concurrent: 1
  
  # 延迟控制
  min_delay: "100ms"
  max_delay: "500ms"
  
  # 超时设置
  timeout: "10s"
  
  # 重试设置
  max_retries: 3
  
  # 停止条件
  ok_to_stop: false
  finishing_threshold: 0
  
  # 默认字典
  default_user_dict:
    - "admin"
    - "root"
    - "administrator"
    - "user"
    - "test"
    - "guest"
  
  default_pass_dict:
    - "123456"
    - "password"
    - "admin"
    - "root"
    - "123456789"
    - "12345678"
  
  # 其他设置
  skip_empty_password: true
  skip_empty_username: true
  only_need_password: false

# 输出设置
output:
  format: "text"  # json, text, csv
  file: ""
  verbose: false
  silent: false
  no_color: false
  show_failed: false

# 代理设置
proxy:
  enabled: false
  type: "http"  # http, https, socks5
  address: ""
  username: ""
  password: ""
